title: Rebecca Consterdine
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://scontent-lht6-1.xx.fbcdn.net/v/t1.0-9/p960x960/111218010_971199046660105_7499021786335841971_o.jpg?_nc_cat=111&_nc_sid=85a577&_nc_ohc=Z7MlGJ5kT1AAX_76eEM&_nc_ht=scontent-lht6-1.xx&_nc_tp=6&oh=38b8d15236bdb9e0d67c742dc6356308&oe=5F3C91B1https://scontent-lht6-1.xx.fbcdn.net/v/t1.0-9/p960x960/111218010_971199046660105_7499021786335841971_o.jpg?_nc_cat=111&_nc_sid=85a577&_nc_ohc=Z7MlGJ5kT1AAX_76eEM&_nc_ht=scontent-lht6-1.xx&_nc_tp=6&oh=38b8d15236bdb9e0d67c742dc6356308&oe=5F3C91B1

description: "‘What is more agreeable than wisdom itself?’ - Marcus Aurelius, Meditations 5.9"
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
